# Some formulae that might be useful in this course
[Python 3.13.2 documentation](https://docs.python.org/3/index.html)

## imports
What might be needed? Only when you're actualy using those packages

For arrays and mathematical functions and more...

In [ ]:
import numpy as np

For plotting

In [ ]:
from matplotlib import pyplot

For showing and saving plots in svg or pdf format.

In [ ]:
from open_atmos_jupyter_utils import show_plot #if not installed run !pip install open-atmos-jupyter-utils

For using units and also be able to turn them off for calculations

In [ ]:
from PySDM.physics import si #if not installed run !pip install PySDM #Fake units

## NumPy arrays
[NumPy website](https://numpy.org)
Examples of functions:
- `np.array`
- `np.zeros`
- `np.ones`
- `np.linspace`

You can find more in [The guide for absolute beginners](https://numpy.org/doc/stable/user/absolute_beginners.html).

In [26]:
import numpy as np

In [27]:
array_from_tuple = np.array((0,1,6,2))
array_from_tuple

array([0, 1, 6, 2])

In [28]:
array_from_tuple_multi = np.array((0,1)*5)
array_from_tuple_multi

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [29]:
shape = (3,4)
array_with_zeros = np.zeros(shape=shape)
array_with_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
array_with_ones = np.ones(shape=shape)
array_with_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
interval = np.linspace(3.4, 7.1, num=5)
interval

array([3.4  , 4.325, 5.25 , 6.175, 7.1  ])

## loops

In [32]:
n= 5

In [33]:
for i in range(n):
    print(f"Index: {i}")
print(range(n))

Index: 0
Index: 1
Index: 2
Index: 3
Index: 4
range(0, 5)


In [34]:
for i, value in enumerate(range(1,n)):
    print(f"Index: {i}, value: {value}")

Index: 0, value: 1
Index: 1, value: 2
Index: 2, value: 3
Index: 3, value: 4


In [37]:
for i in np.linspace(1,2.19, n):
    print(f"Value: {i:.3f}")

Value: 1.000
Value: 1.297
Value: 1.595
Value: 1.893
Value: 2.190


In [40]:
for i in [3/19, 4, .011, 'cow', {'fruits': {'kiwi', 'blueberry'}}, [0,0], np.linspace(-3,0,n)]:
    print(i)

0.15789473684210525
4
0.011
cow
{'fruits': {'kiwi', 'blueberry'}}
[0, 0]
[-3.   -2.25 -1.5  -0.75  0.  ]


## How add something to the np.array or list?


In [42]:
x = []
x.append(1)
print(x)
x.append("hello")
print(x)

[1]
[1, 'hello']


In [57]:
y = np.zeros(shape=(2,4))
print(f"y: {y}")
y[0] = 6
print(f"y: {y}")
y[:,1] = 177
print(f"y: {y}")

y: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
y: [[6. 6. 6. 6.]
 [0. 0. 0. 0.]]
y: [[  6. 177.   6.   6.]
 [  0. 177.   0.   0.]]
